# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 11:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('coo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
